In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
#encode gender column
from sklearn.preprocessing import LabelEncoder
gender_label_encoder=LabelEncoder()
data['Gender']=gender_label_encoder.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
#encode geography column
from sklearn.preprocessing import OneHotEncoder
geo_onehot_encoder=OneHotEncoder()
geo_encoder=geo_onehot_encoder.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [7]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=geo_onehot_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
##combine onehotencoded values with original dataframe
data=pd.concat([data.drop(['Geography'],axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
#save the encoder objects in a pickle file

with open('gender_label_encoder.pkl','wb') as f:
    pickle.dump(gender_label_encoder,f)

with open('geo_onehot_encoder.pkl','wb') as f:
    pickle.dump(geo_onehot_encoder,f)

In [11]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
#Divide the dataset into dependent and independent features
X=data.drop('Exited',axis=1)
y=data['Exited']

#Divide the dataset into Train and Test Features
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=45)

In [13]:
#Standardize the values
standard_scaler=StandardScaler()
X_train=standard_scaler.fit_transform(X_train)
X_test=standard_scaler.transform(X_test)

#save the scaler in the pickle file

with open('standard_scaler.pkl','wb') as f:
    pickle.dump(standard_scaler,f)

### ANN Implementation

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [15]:
X_train.shape[1],

(12,)

In [16]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

/Users/himanidadem/Documents/Krish Naik Gen AI/Section-13/H-Section-13/tf_env/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-05-10 14:47:07.348499: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2026-05-10 14:47:07.348716: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2026-05-10 14:47:07.348748: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2026-05-10 14:47:07.349092: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-10 14:47:07.349125: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
#define optimizers and loss
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
loss=tf.keras.losses.BinaryCrossentropy()
loss

In [19]:
#compile the model
#setup earlystopping and tensorboard
#train the model
#save the model
##visualize the tensorboard

In [20]:
#compile the model
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

#setup earlystopping and tensorboard
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=15,restore_best_weights=True)
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensor_board=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [21]:
#train the model
#training data, epochs, batch size, steps
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[early_stopping_callback,tensor_board])
#save the model

Epoch 1/100

2026-05-10 14:47:09.196009: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.7879 - loss: 0.5369 - val_accuracy: 0.7995 - val_loss: 0.5117
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7545 - loss: 1.1960 - val_accuracy: 0.7795 - val_loss: 0.7438
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7319 - loss: 2.5409 - val_accuracy: 0.8070 - val_loss: 1.0168
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.7360 - loss: 3.9702 - val_accuracy: 0.8160 - val_loss: 1.3758
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7297 - loss: 6.7059 - val_accuracy: 0.7520 - val_loss: 9.3738
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7314 - loss: 7.9371 - val_accuracy: 0.7920 - val_loss: 4.1406
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7408 - loss: 8.2097 - val_accuracy: 0.7960 - val_loss: 2.8527
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7244 - loss: 10.4520 - val_accuracy: 0.7045 - val_loss: 8.9214
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7311 - loss: 16.0164 - val_accuracy: 0.8005 - val_loss: 7.2590
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7316 - loss: 20.7991 - val_accuracy: 0.8065 - val_loss: 9.3569
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7343 - loss: 22.8248 - val_accuracy: 0.6350 - val_loss: 93.6756
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7331 - loss: 28.2429 - val_accuracy: 0.7600 - val_loss: 13.4874
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7306 - loss: 36.4770 - val_accuracy: 0.7535 - val_loss: 33.2804
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7409 - loss: 35.4095 - val_accuracy: 0.7720 - val_loss: 30.3528
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7426 - loss: 27.5489 - val_accuracy: 0.8015 - val_loss: 13.6397
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7218 - loss: 52.0657 - val_accuracy: 0.7915 - val_loss: 31.7074

In [22]:
model.save('model.keras')

In [23]:
## Load tensorboard extension
%load_ext tensorboard

In [24]:
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "/Users/himanidadem/Documents/Krish Naik Gen AI/Section-13/H-Section-13/tf_env/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/Users/himanidadem/Documents/Krish Naik Gen AI/Section-13/H-Section-13/tf_env/lib/python3.10/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File "/Users/himanidadem/Documents/Krish Naik Gen AI/Section-13/H-Section-13/tf_env/lib/python3.10/site-packages/tensorboard/default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [25]:
import sys
!"{sys.executable}" -m pip install --upgrade pip setuptools wheel

Requirement already satisfied: pip in ./tf_env/lib/python3.10/site-packages (26.1.1)
Requirement already satisfied: setuptools in ./tf_env/lib/python3.10/site-packages (82.0.1)
Requirement already satisfied: wheel in ./tf_env/lib/python3.10/site-packages (0.47.0)
Requirement already satisfied: packaging>=24.0 in ./tf_env/lib/python3.10/site-packages (from wheel) (26.2)